#!/usr/bin/env sh

set -e
# set -x

if test -d "$(pwd)/.git"; then
    if [ ! "$UNITED_VENV" ]; then
        export UNITED_VENV=yes
        export UNITED_WORKER_COUNT=$(nproc --ignore=1)
        export PATH="$(pwd):$PATH"
        if [ "x$1" != "x" ]; then
            export UNITED_PREFIX=$1
            shift
        else
            export UNITED_PREFIX=$(pwd)/local/
        fi
        if [ ! "$@" ]; then
            echo ""
            echo "  🚀 🛰  Entering scheme-united environment 🌝 🌱"
            echo ""
            $SHELL
        else
            exec $@
        fi
    else
        echo "You are already in a virtual environment!"
    fi
else
    echo "You need to run $0 from the root of the repository..."
    exit 1
fi
